language: bash
os: linux
services:
    - docker
before_install:
    - docker-compose up -d
    - docker ps -a
script:
    - docker exec -it jobtest-php-fpm /bin/bash -c "/application/vendor/bin/phpunit tests --configuration /application/phpunit.xml"



