language: shell
os: linux
services:
    - docker
before_install:
    - docker-compose up -d
    - docker ps -a
script:
    - docker exec -it jobtest-php-fpm /bin/sh -c "cd /application; composer update; vendor/bin/phpunit tests --configuration phpunit.xml"




