language: bash
os: linux
services:
    - docker
before_install:
    - docker-compose up -d
script:
    - docker exec -it jobtest-php-fpm /bin/bash -c "vendor/bin/phpunit tests --configuration phpunit.xml"



