language: shell
os: linux
services:
    - docker
before_install:
    - docker-compose up -d
    - docker ps -a
script:
    - docker exec -it jobtest-php-fpm /bin/sh -c "/application/vendor/bin/phpunit tests --configuration /application/phpunit.xml"



