version: "2.1"
services:
  php-fpm:
    build:
      dockerfile: ./phpdocker/php-fpm/Dockerfile
      context: ./
    container_name: jobtest-php-fpm
    working_dir: /application
    volumes:
      - ./src:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
        - worktest

  mysql:
      image: mysql:5.6
      container_name: jobtest-mysql
      working_dir: /application
      volumes:
          - ./src:/application
          - ./mysql:/var/lib/mysql
      environment:
          - DB_HOST=jobtest-mysql
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=users
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=password

      ports:
          - "3306:3306"
      healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
      networks:
          - worktest

  webserver:
    image: nginx:alpine
    container_name: jobtest-webserver
    restart: always
    working_dir: /application
    volumes:
      - ./src:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"
    depends_on:
      - php-fpm
    networks:
      - worktest
networks:
  worktest:
      driver: bridge








